In [2]:
# Задание 1.3.1

import numpy as np

x = np.array([[1, 0, 1, 0, 1, 0, 1, 0], [0, 1, 0, 1, 0, 1, 0, 1],
             [1, 0, 1, 0, 1, 0, 1, 0], [0, 1, 0, 1, 0, 1, 0, 1],
             [1, 0, 1, 0, 1, 0, 1, 0], [0, 1, 0, 1, 0, 1, 0, 1],
             [1, 0, 1, 0, 1, 0, 1, 0], [0, 1, 0, 1, 0, 1, 0, 1]])

print(x)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [3]:
# Задание 1.3.2

x = np.arange(0,5)
x =  np.array([x, x, x, x, x])

print(x)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [4]:
# Задание 1.3.3

x = np.random.randint(0, 10, size = (3,3,3))

print(x)

[[[7 0 7]
  [5 6 6]
  [0 6 7]]

 [[5 6 0]
  [3 9 6]
  [8 1 9]]

 [[7 5 0]
  [5 7 5]
  [9 2 4]]]


In [5]:
# Задание 1.3.4

x = np.array([[1, 1, 1],
             [1, 0, 1],
             [1, 1, 1],])

print(x)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


In [6]:
# Задание 1.3.5

x = np.random.randint(0, 10, size = (10,))
print(x)
x = np.sort(x)[::-1]
print(x)

[0 5 7 4 6 0 6 4 5 3]
[7 6 6 5 5 4 4 3 0 0]


In [7]:
# Задание 1.3.6

x = np.random.randint(0, 10, size = (5,5))
print(x)
print(x.shape)
print(x.size)
print(x.ndim)

[[1 4 3 5 7]
 [0 6 1 1 1]
 [4 9 6 7 0]
 [6 2 3 4 5]
 [3 4 9 4 2]]
(5, 5)
25
2


In [8]:
# Задание 2.3.1

import pandas as pd
from math import sqrt

a = pd.Series([1, 2, 3, 4, 5])
b = pd.Series([10, 20, 30, 40, 50])


def eRas(y, z):
  res = 0

  for i in range(len(y)):
    res += (y[i] - z[i]) ** 2

  return sqrt(res)

print(eRas(a, b))

66.74578638386096


In [9]:
# Задание 2.3.2

url = "https://raw.githubusercontent.com/akmand/datasets/main/adult.csv"
dataframe = pd.read_csv(url)

In [10]:
# Задание 2.3.3

dataframe.head(2)

age         workclass  education_num      marital_status       occupation  \
0   39         State-gov             13       Never-married     Adm-clerical   
1   50  Self-emp-not-inc             13  Married-civ-spouse  Exec-managerial   

    relationship   race gender  hours_per_week native_country  capital  \
0  Not-in-family  White   Male              40  United-States     2174   
1        Husband  White   Male              13  United-States        0   

  income_status  
0         <=50K  
1         <=50K

In [11]:
dataframe.tail(3)

age     workclass  education_num      marital_status       occupation  \
45219   38       Private             13  Married-civ-spouse   Prof-specialty   
45220   44       Private             13            Divorced     Adm-clerical   
45221   35  Self-emp-inc             13  Married-civ-spouse  Exec-managerial   

      relationship   race gender  hours_per_week native_country  capital  \
45219      Husband  White   Male              50  United-States        0   
45220    Own-child  Other   Male              40  United-States     5455   
45221      Husband  White   Male              60  United-States        0   

      income_status  
45219         <=50K  
45220         <=50K  
45221          >50K

In [12]:
dataframe.shape

(45222, 12)

In [13]:
dataframe.describe()

age  education_num  hours_per_week       capital
count  45222.000000   45222.000000    45222.000000  45222.000000
mean      38.547941      10.118460       40.938017   1012.834925
std       13.217870       2.552881       12.007508   7530.315380
min       17.000000       1.000000        1.000000  -4356.000000
25%       28.000000       9.000000       40.000000      0.000000
50%       37.000000      10.000000       40.000000      0.000000
75%       47.000000      13.000000       45.000000      0.000000
max       90.000000      16.000000       99.000000  99999.000000

In [14]:
dataframe.iloc[1:4]

age         workclass  education_num      marital_status  \
1   50  Self-emp-not-inc             13  Married-civ-spouse   
2   38           Private              9            Divorced   
3   53           Private              7  Married-civ-spouse   

          occupation   relationship   race gender  hours_per_week  \
1    Exec-managerial        Husband  White   Male              13   
2  Handlers-cleaners  Not-in-family  White   Male              40   
3  Handlers-cleaners        Husband  Other   Male              40   

  native_country  capital income_status  
1  United-States        0         <=50K  
2  United-States        0         <=50K  
3  United-States        0         <=50K

In [15]:
dataframe[dataframe['race'] == 'Other'].head(3)

age workclass  education_num         marital_status         occupation  \
3   53   Private              7     Married-civ-spouse  Handlers-cleaners   
4   28   Private             13     Married-civ-spouse     Prof-specialty   
6   49   Private              5  Married-spouse-absent      Other-service   

    relationship   race  gender  hours_per_week native_country  capital  \
3        Husband  Other    Male              40  United-States        0   
4           Wife  Other  Female              40          Other        0   
6  Not-in-family  Other  Female              16          Other        0   

  income_status  
3         <=50K  
4         <=50K  
6         <=50K

In [18]:
# Задание 3.3.2

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

dframe = pd.read_csv(r'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv')
scaler = MinMaxScaler()
dframe[['sepal_length_cm']] = scaler.fit_transform(dframe[['sepal_length_cm']])
scaler = StandardScaler()
dframe[['sepal_width_cm']] = scaler.fit_transform(dframe[['sepal_width_cm']])
print(dframe)

     sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145 